### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by chindrop**
## Newsweek Clone: Awaiting review

In this project:
- Bootstrap cdn used
- Sections added step by step

### CODE REVIEW

**Comment by lekegitrepo** [comment]
#### Hi @chindrop :+1: 
#### Good job :muscle: the page looks great. However, you need to implement the following requirements before the project can be approved :point_down: 

**_1. Enable stickler for this project._**

**_2. Improve the positioning of the navigation links on the navbar: the search and the search icon should be on the same line with other nav links._** :point_down: 

nav

**_3. The Debate section is missing_** :point_down: 

debate

4. There should be a margin between "SEE ALL FEATURES" and the content below it. :point_down: 

magazine

**_5. The page is broken on the mobile screen size._** :point_down: 

mobile-screen

**_6. Remove comments from the code._**

**_7. Try to improve your pull request message and the commits: "added small comment" is not descriptive._**

**_8. Fix the errors in the CSS style._** :point_down: 

style-error

**_Kindly fix these and submit for review._**

**_if you have any doubts or questions contact me on slack._**

### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by chindrop** [comment]
##Newsweek: Review changes

In this review:
- fixes made to search and search icon
- Broken screen fixed

**Review by rammazzoti2000 — CHANGES_REQUESTED** [review]
# Status: Changes Required :raised_hands: 
### Hello @chindrop :handshake: great job so far on fixing the `navbar`
###
There are still some issues though :pray: that are preventing me to approve this project.
- [ ] The page on small screens is overflowing horizontally, try to read about `overflow-x: hidden;` :point_down:
image

- [ ] On small screens the margin is still missing between "SEE ALL FEATURES" and the content below it. :point_down: 
image
- [ ] The stickler must be enabled read more [here](https://github.com/microverseinc/linters-config/tree/master/css)
###
#### Kindly fix these and submit for review.

#### If you have any doubts or questions contact me on slack.

### Reviewed by Alexandru Bangau.

**Review by rammazzoti2000 — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by chindrop** [comment]
## Note to TSE

In this review:
- Stickler enabled and configuration check again but still is not working so i checked with stye-linter in vscode please do not use against
- Other changes made.

**Comment by trekab** [comment]
# Changes Required!
Hello @chindrop, well done! Your current progress on this project is impressive. However, I would like to direct you to some vital features that you should look at so as to finally complete this project.
* Featured stories should be on top in small screen sizes. compare with [original site](https://www.newsweek.com/)
* Featured slide shows(US, World, Business, Tech & Science) are off on medium screen sizes. compare with [original site](https://www.newsweek.com/)
* Stickler still appears to be disabled for your project.

__Kindly work on the required changes and submit another code review request__
_Feel free to contact me on slack if you need more clarification on the required changes_
__Treasure Kabareebe__

**Comment by chindrop** [comment]
- Reviewed changes made

**Comment by lekegitrepo** [comment]
#### Hi @chindrop :+1: 
#### You have done an excellent job :muscle: However, based on the last review of which you have fixed the page display on the medium screen but there's a horizontal scroll bar on the page. Try to fix this.

### Reviewed by Temitayo Adeleke.

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by trekab** [comment]
# Approved! :tada: 
Well done @chindrop! :clap: You may merge to master, fill the project completion form, and proceed to your next project.

_Happy coding!_ :smile: 
__Treasure Kabareebe__

**Pull request merged**
